// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package go_micro_service_user

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	//注册
	Register(ctx context.Context, in *UserRegisterReq, opts ...client.CallOption) (*UserRegisterAck, error)
	//登录
	Login(ctx context.Context, in *UserLoginReq, opts ...client.CallOption) (*UserLoginAck, error)
	//获取信息
	GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...client.CallOption) (*UserInfoAck, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Register(ctx context.Context, in *UserRegisterReq, opts ...client.CallOption) (*UserRegisterAck, error) {
	req := c.c.NewRequest(c.name, "User.Register", in)
	out := new(UserRegisterAck)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *UserLoginReq, opts ...client.CallOption) (*UserLoginAck, error) {
	req := c.c.NewRequest(c.name, "User.Login", in)
	out := new(UserLoginAck)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...client.CallOption) (*UserInfoAck, error) {
	req := c.c.NewRequest(c.name, "User.GetUserInfo", in)
	out := new(UserInfoAck)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	//注册
	Register(context.Context, *UserRegisterReq, *UserRegisterAck) error
	//登录
	Login(context.Context, *UserLoginReq, *UserLoginAck) error
	//获取信息
	GetUserInfo(context.Context, *UserInfoReq, *UserInfoAck) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Register(ctx context.Context, in *UserRegisterReq, out *UserRegisterAck) error
		Login(ctx context.Context, in *UserLoginReq, out *UserLoginAck) error
		GetUserInfo(ctx context.Context, in *UserInfoReq, out *UserInfoAck) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Register(ctx context.Context, in *UserRegisterReq, out *UserRegisterAck) error {
	return h.UserHandler.Register(ctx, in, out)
}

func (h *userHandler) Login(ctx context.Context, in *UserLoginReq, out *UserLoginAck) error {
	return h.UserHandler.Login(ctx, in, out)
}

func (h *userHandler) GetUserInfo(ctx context.Context, in *UserInfoReq, out *UserInfoAck) error {
	return h.UserHandler.GetUserInfo(ctx, in, out)
}
